blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://docs.github.com
    about: Check our documentation for help.
